### PR TITLE
Added tapNavigation

### PR DESCRIPTION
**Pull request by sjsakib**
Don't merge this PR yet. I have a few more issues to discuss

### CODE REVIEW

**Comment by sjsakib** [comment]
1. `react-native-gesture-handler` has to be installed and configured. Should be mentioned in the docs.
2. The slider gets a little blurred when scaled up with transform. We could use width and height to scale maybe. 
3. What do line [128](https://github.com/repodio/react-native-scrubber/blob/ebf0c2131b22cc442f1097729efab19edbc9cff5/index.js#L128)-123 do? I've seen that, the component works fine without them.
4. It would be nice to be able to control the `hitSlop` for the slider with props (optionally). 
5. There are some typos, and trailing white spaces in the code, I can fix them and format the code with prettier if you want.

**Comment by CapitanRedBeard** [comment]
@sjsakib

**Comment by sjsakib** [comment]
Okay, I've removed the unnecessary code.
It turns out using width and height instead of transform will have performance drawback, so let's keep it as it is. Most people won't notice the blur anyway since the slider will be under their finger while scrubbing :stuck_out_tongue:

**Comment by sjsakib** [comment]
@CapitanRedBeard, is this one going to be merged?

**Pull request merged**
